### ISSUE TITLE
Inteface defaults

### ISSUE THREAD

**Issue by MarceloBaeza** [ssanderson/python-interface#41]
Hi,
First, I thanks you by this lib, is very good.
I have a question, is its possible omite or remove the messages from @interface.default when I use variables?
`The following attributes are used but are not part of the interface:
  - key`
oh! I have other question, Is it possible instantiate a interface ?
Example:
![image](https://user-images.githubusercontent.com/22486330/98964787-02a03b00-24e8-11eb-9598-eed4275097e9.png)
Can I use this "variable = InterfaceGenericKeyValue()" ?

**Comment by ssanderson** [comment]
@MarceloBaeza sorry for the long delay in replying here.

> I have a question, is its possible omite or remove the messages from @interface.default when I use variables?

There's no way to disable these warnings. The purpose of `@default` is to allow you to provide default implementations of methods that should be valid for **any** implementation of the rest of the interface methods. In your example above, your defaults are assuming that the `key` and `value` attributes are present on the type implementing the interface, but those attributes aren't part of the interface, so we warn.

> Is it possible instantiate a interface ?

It isn't possible to instantiate an interface. An interface is an abstract description of methods that should be provided by some other type. You should create an implementation of the interface using `implements(IFace)` and instantiate that implementation type.
